apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: yaude-icloud-vue2
  description: Node VUe3.0 Sample App
  tags:
    - app-accelerator
    - node
    - express
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=yaude-icloud-vue2'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
